// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHZDgPoUZNlf6alF29mm8YWwL-l-2z_E',
    appId: '1:990505426962:web:ac1b6997b552338ed438cb',
    messagingSenderId: '990505426962',
    projectId: 'connectify-7db57',
    authDomain: 'connectify-7db57.firebaseapp.com',
    storageBucket: 'connectify-7db57.firebasestorage.app',
    measurementId: 'G-DBJ1EFF7NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRmf95EhtwtF6oDm-F35iPR107aRQo2XY',
    appId: '1:990505426962:android:70068282fba74c47d438cb',
    messagingSenderId: '990505426962',
    projectId: 'connectify-7db57',
    storageBucket: 'connectify-7db57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjuOxErczmrdevreoSClDkUHFqM-puLo',
    appId: '1:990505426962:ios:25baa9f9a87a45bcd438cb',
    messagingSenderId: '990505426962',
    projectId: 'connectify-7db57',
    storageBucket: 'connectify-7db57.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjuOxErczmrdevreoSClDkUHFqM-puLo',
    appId: '1:990505426962:ios:25baa9f9a87a45bcd438cb',
    messagingSenderId: '990505426962',
    projectId: 'connectify-7db57',
    storageBucket: 'connectify-7db57.firebasestorage.app',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfHZDgPoUZNlf6alF29mm8YWwL-l-2z_E',
    appId: '1:990505426962:web:29501fe8dca1e866d438cb',
    messagingSenderId: '990505426962',
    projectId: 'connectify-7db57',
    authDomain: 'connectify-7db57.firebaseapp.com',
    storageBucket: 'connectify-7db57.firebasestorage.app',
    measurementId: 'G-558N7Q5TH5',
  );
}
